version: '3.7'
services:
  bot:
    build: 
      context: .
      dockerfile: "dockerfile.bot"
    image: "argbot:latest"
    env_file:
    - docker.env
    depends_on:
    - "db"
  db:
    image: "postgres:latest"
    restart: always
    env_file:
    - docker.env
      
